name: milho
version: 0.1.0.0
github: "celsobonutti/milho"
license: BSD3
author: "Celso Bonutti"
maintainer: "i.am@cel.so"
copyright: "Celso Bonutti"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/celsobonutti/milho#readme>

dependencies:
  - base                >= 4.17.0   && < 5
  - parser-combinators  >= 1.3.0    && < 2.0
  - containers          >= 0.6.5.1  && < 0.7
  - megaparsec          >= 9.2.0    && < 10.0
  - file-embed          >= 0.0.14.0 && < 0.0.15.0
  - capability          >= 0.5.0    && < 0.6
  - text                >= 2.0      && < 2.1
  - directory           >= 1.3.6.0  && < 1.4
  - filepath            >= 1.4.2.1  && < 1.5
  - mtl                 >= 2.2.2    && < 2.3

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - DisambiguateRecordFields
  - NamedFieldPuns
  - DataKinds
  - DeriveGeneric
  - DerivingVia
  - FlexibleContexts
  - TypeApplications
  - DuplicateRecordFields
  - LambdaCase
  - PatternSynonyms
  - ViewPatterns
  - ConstraintKinds
  - ScopedTypeVariables
  - OverloadedRecordDot
  - NoFieldSelectors

library:
  source-dirs: src

executables:
  milho-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - milho

tests:
  milho-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - milho
      - hspec
      - QuickCheck
      - quickcheck-text
      - string-interpolate

when:
  condition: flag(incomplete-error)
  ghc-options:
    - -Werror=missing-fields
    - -Werror=missing-methods

flags:
  incomplete-error:
    description: >
      Incomplete patterns, missing record fields, and missing class methods are
      an error
    manual: false
    default: true
